### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by Nikkolast88** [element-plus/unplugin-element-plus#14]
demo:
[https://github.com/DengRiGuang/micro-main.git](url)
```
TypeError: require(...) is not a function
    at Object.<anonymous> (D:\My\micro-main\vue.config.js:83:47)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at exports.loadModule (D:\My\micro-main\node_modules\.pnpm\@vue+cli-shared-utils@5.0.0-beta.6\node_modules\@vue\cli-shared-utils\lib\module.js:86:14)
    at loadFileConfig (D:\My\micro-main\node_modules\.pnpm\@vue+cli-service@5.0.0-beta.6_63236f192bf91a0f67fdebc0d8d51b25\node_modules\@vue\cli-service\lib\util\loadFileConfig.js:30:20)
    at Service.loadUserOptions (D:\My\micro-main\node_modules\.pnpm\@vue+cli-service@5.0.0-beta.6_63236f192bf91a0f67fdebc0d8d51b25\node_modules\@vue\cli-service\lib\Service.js:323:44)
```
v0.1.0：
![image](https://user-images.githubusercontent.com/24350210/138043789-7916927f-cca6-43d4-9983-e4445d43bec3.png)

v0.1.3：
![image](https://user-images.githubusercontent.com/24350210/138043589-d37aa676-27a2-4efc-9f5c-3a941969cd6a.png)

**Comment by Michael-py001** [comment]
官方的案例文档居然不更新，真的坑不少人啊

**Comment by bossikill** [comment]
被坑+1
