### ISSUE TITLE
How to use with nuxt 3?

### ISSUE THREAD

**Issue by cawa-93** [element-plus/unplugin-element-plus#150]
Hello. I can't figure out how to use this plugin with nux 3. Can anyone help me? I tried to use it as a plugin for Vite, but I get errors:
```vue
<script setup lang="ts">
import { ElButton } from "element-plus";
</script>

<template>
  <main>
    <el-button>text</el-button>
  </main>
</template>
```
```node
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /home/cawa-93/dev/blog_kyivska_zefirka/node_modules/element-plus/theme-chalk/el-button.css
    at new NodeError (node:internal/errors:372:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at ESMLoader.load (node:internal/modules/esm/loader:407:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:345:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:304:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:82:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
[Vue Router warn]: uncaught error during route navigation:
Error: [vite dev] Error loading external "/home/cawa-93/dev/blog_kyivska_zefirka/node_modules/element-plus/es/components/button/style/css.mjs".
    at file:///home/cawa-93/dev/blog_kyivska_zefirka/.nuxt/dist/server/server.mjs:6517:11
    at async __instantiateModule__ (file:///home/cawa-93/dev/blog_kyivska_zefirka/.nuxt/dist/server/server.mjs:7456:3)
[Vue Router warn]: uncaught error during route navigation:
TypeError: Cannot read properties of undefined (reading '__vccOpts')
    at /home/cawa-93/dev/blog_kyivska_zefirka/node_modules/vue-router/dist/vue-router.cjs.js:2042:55
[nuxt] [request error] [vite dev] Error loading external "/home/cawa-93/dev/blog_kyivska_zefirka/node_modules/element-plus/es/components/button/style/css.mjs".
  at ./.nuxt/dist/server/server.mjs:6517:11
  at async __instantiateModule__ (./.nuxt/dist/server/server.mjs:7456:3)
[Vue Router warn]: uncaught error during route navigation:
TypeError: Cannot read properties of undefined (reading '__vccOpts')
    at /home/cawa-93/dev/blog_kyivska_zefirka/node_modules/vue-router/dist/vue-router.cjs.js:2042:55
[Vue Router warn]: Component "default" in record with path "/" is not a valid component. Received "undefined".
[Vue Router warn]: uncaught error during route navigation:
Error: Invalid route component
    at extractComponentsGuards (/home/cawa-93/dev/blog_kyivska_zefirka/node_modules/vue-router/dist/vue-router.cjs.js:1994:27)
    at /home/cawa-93/dev/blog_kyivska_zefirka/node_modules/vue-router/dist/vue-router.cjs.js:3150:22
    at async file:///home/cawa-93/dev/blog_kyivska_zefirka/.nuxt/dist/server/server.mjs:5239:7
    at async createNuxtAppServer (file:///home/cawa-93/dev/blog_kyivska_zefirka/.nuxt/dist/server/server.mjs:47:7)
    at async Object.renderToString (file:///home/cawa-93/dev/blog_kyivska_zefirka/node_modules/vue-bundle-renderer/dist/index.mjs:264:19)
    at async file:///home/cawa-93/dev/blog_kyivska_zefirka/.nuxt/dev/index.mjs:3038:20
    at async file:///home/cawa-93/dev/blog_kyivska_zefirka/node_modules/h3/dist/index.mjs:420:19
    at async nodeHandler (file:///home/cawa-93/dev/blog_kyivska_zefirka/node_modules/h3/dist/index.mjs:370:7)
    at async ufetch (file:///home/cawa-93/dev/blog_kyivska_zefirka/node_modules/unenv/runtime/fetch/index.mjs:9:17)
    at async $fetchRaw2 (file:///home/cawa-93/dev/blog_kyivska_zefirka/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
✔ Vite server built in 130ms      
```

**Comment by uioz** [comment]
try this:
```typescript
import { defineNuxtConfig } from "nuxt";
import ElementPlus from "unplugin-element-plus/vite";

const lifecycle = process.env.npm_lifecycle_event;

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  typescript: {
    strict: true,
    shim: false,
  },
  build: {
    transpile:
      lifecycle === "build" || lifecycle === "generate" ? ["element-plus"] : [],
  },
  vite: {
    ssr: {
      noExternal: ["element-plus/es"],
    },
    plugins: [ElementPlus()],
  },
});

```

**Comment by sxzz** [comment]
Refer to https://github.com/element-plus/element-plus-nuxt-starter/commit/09c84c050fae55600957cd89dba143ba8363fed0
